### ISSUE TITLE
css.walkDecls is not a function

### ISSUE THREAD

**Issue by zhangsanshi** [yuezk/postcss-urlrev#2]
window10
node 4.2.4
npm 3.5.2 
css.walkDecls is not a function

**Comment by yuezk** [comment]
`npm ls postcss` 输出什么？

**Comment by yuezk** [comment]
依赖的 PostCSS 的版本问题。

当时将 `postcss-urlrev` 中的 `eachDecl`（PostCSS 4.x 中提供的 API） 换为 `walkDecls`（PostCSS 5.x 提供的 API） 时，没有将 `postcss-urlrev` 升级到大版本号（2.0.0），只是升级了一个小版本号（1.1.1）。

但实际情况是这个 API 的改动是不兼容之前的版本的，因此导致了一些项目中如果使用的是 `1.1.0` 或之前的版本，并且 `package.json` 的 `dependencies` 一项中 `postcss-urlrev` 的值是 `^1.1.0`，那么当其他人通过 `npm install` 安装后再使用时就会出现这个错误。

解决办法有两个：
1. 将 `package.json` 中 `postcss-urlrev` 的依赖改为 `=1.1.0`，删除 `node_modules` 然后再重新安装；
2. 将项目中所有依赖 `PostCSS` 的模块升级到最新版本。

方法 1 操作相对简单，但最后还是要根据项目的实际情况选择这两种方法。
