### ISSUE TITLE
Can we replace a `getHash` function?

### ISSUE THREAD

**Issue by tailhook** [yuezk/postcss-urlrev#3]
Hi! Thank you for a nice plugin.

We just want to customize a hashing function to match other parts of our infrastructure. Firstly we need sha1 hash, but most importantly we want to load a hash from a list of hashes rather than reading the actual file.

So it would be cool to have a setting:

```
postcss([urlrev({
    hashFunction: (filename) => HASHES[filename],
})])
```

This should be trivial to implement. Let me know, if you want me to make a pull request.

**Comment by yuezk** [comment]
Added in v1.3.0

**Comment by tailhook** [comment]
Thank was quick. Thanks a lot!
