### ISSUE TITLE
Update for PostCSS 8

### ISSUE THREAD

**Issue by kubijo** [yuezk/postcss-urlrev#7]
Hello, do you have any plans to update the plugin to support new PostCSS?
Here is a guide: https://evilmartians.com/chronicles/postcss-8-plugin-migration

**Comment by yuezk** [comment]
Ok, I think I can migrate it to support PostCSS 8.0.

**Comment by kubijo** [comment]
Hello... is there any chance you'd get into that migration?

**Comment by yuezk** [comment]
I'll try this weekend. Sorry for the delay.

**Comment by kubijo** [comment]
That is quite alright… it does still work for the time being & I'm sure you have a lot on your plate, as almost everybody does.

Thanks.

**Comment by yuezk** [comment]
@kubijo migrated to support PostCSS 8.x, please use the latest version.
